fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - aliyun:22122

upload:
  base-url: aliyun
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
